// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: scan_events.
// - Entity ID: 102019c02702c91762f97631e30307f1639.
// - Entity Version: 102019c029648c97a0184332f6efc1ed1ba.
// - Task ID: 69797e5f2b7be3e86f37954e.
// - Task Root ID: 6967100a73f7f38197307ba3.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for ScanEventsDirection
 */
export enum ScanEventsDirection {
  Unspecified = 0,
  IN = 1,
  OUT = 2,
}



/**
 * Interface for ScanEventsModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface ScanEventsModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  scanned_at: string;
  direction: ScanEventsDirection;
  source?: string | null;
  device_label?: string | null;
  student_id: string;
  location_id: string;
}

/**
 * ORM class for ScanEvents entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class ScanEventsORM {
  private static instance: ScanEventsORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019c02702c91762f97631e30307f1639';
    this.entityName = 'scan_events';
    this.entityVersion = '102019c029648c97a0184332f6efc1ed1ba';
    this.taskId = '69797e5f2b7be3e86f37954e';
    this.taskRootId = '6967100a73f7f38197307ba3';
  }

  /**
   * Get singleton instance of ScanEventsORM
   */
  public static getInstance(): ScanEventsORM {
    if (!ScanEventsORM.instance) {
      ScanEventsORM.instance = new ScanEventsORM();
    }
    
    return ScanEventsORM.instance;
  }

  /**
   * Get scan_events by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getScanEventsByIDs(ids: string[]): Promise<ScanEventsModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete scan_events by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteScanEventsByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all ScanEvents records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllScanEvents(): Promise<ScanEventsModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new ScanEvents record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertScanEvents(data: ScanEventsModel[]): Promise<ScanEventsModel[]> {
    const structured = data.map((item) => CreateData(ScanEventsModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all ScanEvents records
   */
  async purgeAllScanEvents(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List ScanEvents records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listScanEvents(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[ScanEventsModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get scan_events by Id index
   * This function gets data by index.
   */
  async getScanEventsById(
    id: string,
  ): Promise<ScanEventsModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) scan_events by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setScanEventsById(
    id: string,
    data: ScanEventsModel
  ): Promise<ScanEventsModel[]> {
    const index = createIndexId(
      id
    );

    const values = ScanEventsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete scan_events by Id index
   */
  async deleteScanEventsById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get scan_events by DataCreator index
   * This function gets data by index.
   */
  async getScanEventsByDataCreator(
    data_creator: string,
  ): Promise<ScanEventsModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) scan_events by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setScanEventsByDataCreator(
    data_creator: string,
    data: ScanEventsModel
  ): Promise<ScanEventsModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = ScanEventsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete scan_events by DataCreator index
   */
  async deleteScanEventsByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get scan_events by DataUpdater index
   * This function gets data by index.
   */
  async getScanEventsByDataUpdater(
    data_updater: string,
  ): Promise<ScanEventsModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) scan_events by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setScanEventsByDataUpdater(
    data_updater: string,
    data: ScanEventsModel
  ): Promise<ScanEventsModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = ScanEventsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete scan_events by DataUpdater index
   */
  async deleteScanEventsByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get scan_events by StudentId index
   * This function gets data by index.
   */
  async getScanEventsByStudentId(
    student_id: string,
  ): Promise<ScanEventsModel[]> {
    const index = createIndexStudentId(
      student_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) scan_events by StudentId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setScanEventsByStudentId(
    student_id: string,
    data: ScanEventsModel
  ): Promise<ScanEventsModel[]> {
    const index = createIndexStudentId(
      student_id
    );

    const values = ScanEventsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete scan_events by StudentId index
   */
  async deleteScanEventsByStudentId(
    student_id: string
  ): Promise<void> {
    const index = createIndexStudentId(
      student_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get scan_events by LocationId index
   * This function gets data by index.
   */
  async getScanEventsByLocationId(
    location_id: string,
  ): Promise<ScanEventsModel[]> {
    const index = createIndexLocationId(
      location_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) scan_events by LocationId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setScanEventsByLocationId(
    location_id: string,
    data: ScanEventsModel
  ): Promise<ScanEventsModel[]> {
    const index = createIndexLocationId(
      location_id
    );

    const values = ScanEventsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete scan_events by LocationId index
   */
  async deleteScanEventsByLocationId(
    location_id: string
  ): Promise<void> {
    const index = createIndexLocationId(
      location_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get scan_events by ScannedAt index
   * This function gets data by index.
   */
  async getScanEventsByScannedAt(
    scanned_at: string,
  ): Promise<ScanEventsModel[]> {
    const index = createIndexScannedAt(
      scanned_at
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) scan_events by ScannedAt index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setScanEventsByScannedAt(
    scanned_at: string,
    data: ScanEventsModel
  ): Promise<ScanEventsModel[]> {
    const index = createIndexScannedAt(
      scanned_at
    );

    const values = ScanEventsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete scan_events by ScannedAt index
   */
  async deleteScanEventsByScannedAt(
    scanned_at: string
  ): Promise<void> {
    const index = createIndexScannedAt(
      scanned_at
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to ScanEventsModel data array
   */
  private resultToData(values: Data[]): ScanEventsModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return ScanEventsModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as ScanEventsModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized ScanEventsModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is ScanEventsModel => item !== null);
  }
}

/**
 * Convert ScanEventsModel data to Value array
 */
function ScanEventsModelToValues(data: ScanEventsModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'scanned_at', type: DataType.string, defaultValue: '' },
    { key: 'direction', type: DataType.enumeration, defaultValue: 0 },
    { key: 'source', type: DataType.string, defaultValue: null },
    { key: 'device_label', type: DataType.string, defaultValue: null },
    { key: 'student_id', type: DataType.string, defaultValue: '' },
    { key: 'location_id', type: DataType.string, defaultValue: '' },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof ScanEventsModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to ScanEventsModel data
 */
function ScanEventsModelFromValues(values: Value[]): ScanEventsModel {
  const data: Partial<ScanEventsModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'scanned_at':
        data.scanned_at = ParseValue(value, DataType.string) as string;
        break;
      case 'direction':
        data.direction = ParseValue(value, DataType.enumeration) as ScanEventsDirection;
        break;
      case 'source':
        data.source = ParseValue(value, DataType.string) as string | null;
        break;
      case 'device_label':
        data.device_label = ParseValue(value, DataType.string) as string | null;
        break;
      case 'student_id':
        data.student_id = ParseValue(value, DataType.string) as string;
        break;
      case 'location_id':
        data.location_id = ParseValue(value, DataType.string) as string;
        break;
    }
  }
  
  return data as ScanEventsModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for StudentId fields
 */
function createIndexStudentId(
  student_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, student_id, 'student_id'),
  ];

  return {
    fields: ['student_id'],
    values
  };
}
/**
 * Create index for LocationId fields
 */
function createIndexLocationId(
  location_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, location_id, 'location_id'),
  ];

  return {
    fields: ['location_id'],
    values
  };
}
/**
 * Create index for ScannedAt fields
 */
function createIndexScannedAt(
  scanned_at: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, scanned_at, 'scanned_at'),
  ];

  return {
    fields: ['scanned_at'],
    values
  };
}

export default ScanEventsORM;