// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: students.
// - Entity ID: 102019c02702c917356a3415681ca0deeea.
// - Entity Version: 102019c029648c97a0184332f6efc1ed1ba.
// - Task ID: 69797e5f2b7be3e86f37954e.
// - Task Root ID: 6967100a73f7f38197307ba3.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for StudentsModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface StudentsModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  full_name: string;
  grade?: string | null;
  school_id_no: string;
  school_id: string;
  is_active: boolean;
}

/**
 * ORM class for Students entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class StudentsORM {
  private static instance: StudentsORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019c02702c917356a3415681ca0deeea';
    this.entityName = 'students';
    this.entityVersion = '102019c029648c97a0184332f6efc1ed1ba';
    this.taskId = '69797e5f2b7be3e86f37954e';
    this.taskRootId = '6967100a73f7f38197307ba3';
  }

  /**
   * Get singleton instance of StudentsORM
   */
  public static getInstance(): StudentsORM {
    if (!StudentsORM.instance) {
      StudentsORM.instance = new StudentsORM();
    }
    
    return StudentsORM.instance;
  }

  /**
   * Get students by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getStudentsByIDs(ids: string[]): Promise<StudentsModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete students by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteStudentsByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Students records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllStudents(): Promise<StudentsModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Students record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertStudents(data: StudentsModel[]): Promise<StudentsModel[]> {
    const structured = data.map((item) => CreateData(StudentsModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Students records
   */
  async purgeAllStudents(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Students records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listStudents(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[StudentsModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get students by Id index
   * This function gets data by index.
   */
  async getStudentsById(
    id: string,
  ): Promise<StudentsModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) students by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setStudentsById(
    id: string,
    data: StudentsModel
  ): Promise<StudentsModel[]> {
    const index = createIndexId(
      id
    );

    const values = StudentsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete students by Id index
   */
  async deleteStudentsById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get students by DataCreator index
   * This function gets data by index.
   */
  async getStudentsByDataCreator(
    data_creator: string,
  ): Promise<StudentsModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) students by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setStudentsByDataCreator(
    data_creator: string,
    data: StudentsModel
  ): Promise<StudentsModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = StudentsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete students by DataCreator index
   */
  async deleteStudentsByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get students by DataUpdater index
   * This function gets data by index.
   */
  async getStudentsByDataUpdater(
    data_updater: string,
  ): Promise<StudentsModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) students by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setStudentsByDataUpdater(
    data_updater: string,
    data: StudentsModel
  ): Promise<StudentsModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = StudentsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete students by DataUpdater index
   */
  async deleteStudentsByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get students by SchoolId index
   * This function gets data by index.
   */
  async getStudentsBySchoolId(
    school_id: string,
  ): Promise<StudentsModel[]> {
    const index = createIndexSchoolId(
      school_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) students by SchoolId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setStudentsBySchoolId(
    school_id: string,
    data: StudentsModel
  ): Promise<StudentsModel[]> {
    const index = createIndexSchoolId(
      school_id
    );

    const values = StudentsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete students by SchoolId index
   */
  async deleteStudentsBySchoolId(
    school_id: string
  ): Promise<void> {
    const index = createIndexSchoolId(
      school_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get students by IsActive index
   * This function gets data by index.
   */
  async getStudentsByIsActive(
    is_active: boolean,
  ): Promise<StudentsModel[]> {
    const index = createIndexIsActive(
      is_active
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) students by IsActive index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setStudentsByIsActive(
    is_active: boolean,
    data: StudentsModel
  ): Promise<StudentsModel[]> {
    const index = createIndexIsActive(
      is_active
    );

    const values = StudentsModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete students by IsActive index
   */
  async deleteStudentsByIsActive(
    is_active: boolean
  ): Promise<void> {
    const index = createIndexIsActive(
      is_active
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to StudentsModel data array
   */
  private resultToData(values: Data[]): StudentsModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return StudentsModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as StudentsModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized StudentsModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is StudentsModel => item !== null);
  }
}

/**
 * Convert StudentsModel data to Value array
 */
function StudentsModelToValues(data: StudentsModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'full_name', type: DataType.string, defaultValue: '' },
    { key: 'grade', type: DataType.string, defaultValue: null },
    { key: 'school_id_no', type: DataType.string, defaultValue: '' },
    { key: 'school_id', type: DataType.string, defaultValue: '' },
    { key: 'is_active', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof StudentsModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to StudentsModel data
 */
function StudentsModelFromValues(values: Value[]): StudentsModel {
  const data: Partial<StudentsModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'full_name':
        data.full_name = ParseValue(value, DataType.string) as string;
        break;
      case 'grade':
        data.grade = ParseValue(value, DataType.string) as string | null;
        break;
      case 'school_id_no':
        data.school_id_no = ParseValue(value, DataType.string) as string;
        break;
      case 'school_id':
        data.school_id = ParseValue(value, DataType.string) as string;
        break;
      case 'is_active':
        data.is_active = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as StudentsModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for SchoolId fields
 */
function createIndexSchoolId(
  school_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, school_id, 'school_id'),
  ];

  return {
    fields: ['school_id'],
    values
  };
}
/**
 * Create index for IsActive fields
 */
function createIndexIsActive(
  is_active: boolean
): Index {
  const values: Value[] = [
    CreateValue(DataType.boolean, is_active, 'is_active'),
  ];

  return {
    fields: ['is_active'],
    values
  };
}

export default StudentsORM;