// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: demo_request.
// - Entity ID: 102019bba986c877897bf4c01f45a4891a0.
// - Entity Version: 102019bba984a827efcba1e180f1cd79287.
// - Task ID: 6967100a73f7f38197307ba3.
// - Task Root ID: 6967100a73f7f38197307ba3.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for DemoRequestModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface DemoRequestModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  school_name: string;
  contact_person_name: string;
  contact_email: string;
  contact_phone?: string | null;
  student_count: number;
  preferred_demo_time?: string | null;
  additional_notes?: string | null;
}

/**
 * ORM class for DemoRequest entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class DemoRequestORM {
  private static instance: DemoRequestORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019bba986c877897bf4c01f45a4891a0';
    this.entityName = 'demo_request';
    this.entityVersion = '102019bba984a827efcba1e180f1cd79287';
    this.taskId = '6967100a73f7f38197307ba3';
    this.taskRootId = '6967100a73f7f38197307ba3';
  }

  /**
   * Get singleton instance of DemoRequestORM
   */
  public static getInstance(): DemoRequestORM {
    if (!DemoRequestORM.instance) {
      DemoRequestORM.instance = new DemoRequestORM();
    }
    
    return DemoRequestORM.instance;
  }

  /**
   * Get demo_request by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getDemoRequestByIDs(ids: string[]): Promise<DemoRequestModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete demo_request by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteDemoRequestByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all DemoRequest records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllDemoRequest(): Promise<DemoRequestModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new DemoRequest record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertDemoRequest(data: DemoRequestModel[]): Promise<DemoRequestModel[]> {
    const structured = data.map((item) => CreateData(DemoRequestModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all DemoRequest records
   */
  async purgeAllDemoRequest(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List DemoRequest records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listDemoRequest(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[DemoRequestModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get demo_request by Id index
   * This function gets data by index.
   */
  async getDemoRequestById(
    id: string,
  ): Promise<DemoRequestModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) demo_request by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDemoRequestById(
    id: string,
    data: DemoRequestModel
  ): Promise<DemoRequestModel[]> {
    const index = createIndexId(
      id
    );

    const values = DemoRequestModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete demo_request by Id index
   */
  async deleteDemoRequestById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get demo_request by DataCreator index
   * This function gets data by index.
   */
  async getDemoRequestByDataCreator(
    data_creator: string,
  ): Promise<DemoRequestModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) demo_request by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDemoRequestByDataCreator(
    data_creator: string,
    data: DemoRequestModel
  ): Promise<DemoRequestModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = DemoRequestModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete demo_request by DataCreator index
   */
  async deleteDemoRequestByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get demo_request by DataUpdater index
   * This function gets data by index.
   */
  async getDemoRequestByDataUpdater(
    data_updater: string,
  ): Promise<DemoRequestModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) demo_request by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDemoRequestByDataUpdater(
    data_updater: string,
    data: DemoRequestModel
  ): Promise<DemoRequestModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = DemoRequestModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete demo_request by DataUpdater index
   */
  async deleteDemoRequestByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get demo_request by ContactEmail index
   * This function gets data by index.
   */
  async getDemoRequestByContactEmail(
    contact_email: string,
  ): Promise<DemoRequestModel[]> {
    const index = createIndexContactEmail(
      contact_email
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) demo_request by ContactEmail index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDemoRequestByContactEmail(
    contact_email: string,
    data: DemoRequestModel
  ): Promise<DemoRequestModel[]> {
    const index = createIndexContactEmail(
      contact_email
    );

    const values = DemoRequestModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete demo_request by ContactEmail index
   */
  async deleteDemoRequestByContactEmail(
    contact_email: string
  ): Promise<void> {
    const index = createIndexContactEmail(
      contact_email
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get demo_request by SchoolName index
   * This function gets data by index.
   */
  async getDemoRequestBySchoolName(
    school_name: string,
  ): Promise<DemoRequestModel[]> {
    const index = createIndexSchoolName(
      school_name
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) demo_request by SchoolName index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDemoRequestBySchoolName(
    school_name: string,
    data: DemoRequestModel
  ): Promise<DemoRequestModel[]> {
    const index = createIndexSchoolName(
      school_name
    );

    const values = DemoRequestModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete demo_request by SchoolName index
   */
  async deleteDemoRequestBySchoolName(
    school_name: string
  ): Promise<void> {
    const index = createIndexSchoolName(
      school_name
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get demo_request by CreateTime index
   * This function gets data by index.
   */
  async getDemoRequestByCreateTime(
    create_time: string,
  ): Promise<DemoRequestModel[]> {
    const index = createIndexCreateTime(
      create_time
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) demo_request by CreateTime index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setDemoRequestByCreateTime(
    create_time: string,
    data: DemoRequestModel
  ): Promise<DemoRequestModel[]> {
    const index = createIndexCreateTime(
      create_time
    );

    const values = DemoRequestModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete demo_request by CreateTime index
   */
  async deleteDemoRequestByCreateTime(
    create_time: string
  ): Promise<void> {
    const index = createIndexCreateTime(
      create_time
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to DemoRequestModel data array
   */
  private resultToData(values: Data[]): DemoRequestModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return DemoRequestModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as DemoRequestModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized DemoRequestModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is DemoRequestModel => item !== null);
  }
}

/**
 * Convert DemoRequestModel data to Value array
 */
function DemoRequestModelToValues(data: DemoRequestModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'school_name', type: DataType.string, defaultValue: '' },
    { key: 'contact_person_name', type: DataType.string, defaultValue: '' },
    { key: 'contact_email', type: DataType.string, defaultValue: '' },
    { key: 'contact_phone', type: DataType.string, defaultValue: null },
    { key: 'student_count', type: DataType.number, defaultValue: 0 },
    { key: 'preferred_demo_time', type: DataType.string, defaultValue: null },
    { key: 'additional_notes', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof DemoRequestModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to DemoRequestModel data
 */
function DemoRequestModelFromValues(values: Value[]): DemoRequestModel {
  const data: Partial<DemoRequestModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'school_name':
        data.school_name = ParseValue(value, DataType.string) as string;
        break;
      case 'contact_person_name':
        data.contact_person_name = ParseValue(value, DataType.string) as string;
        break;
      case 'contact_email':
        data.contact_email = ParseValue(value, DataType.string) as string;
        break;
      case 'contact_phone':
        data.contact_phone = ParseValue(value, DataType.string) as string | null;
        break;
      case 'student_count':
        data.student_count = ParseValue(value, DataType.number) as number;
        break;
      case 'preferred_demo_time':
        data.preferred_demo_time = ParseValue(value, DataType.string) as string | null;
        break;
      case 'additional_notes':
        data.additional_notes = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as DemoRequestModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for ContactEmail fields
 */
function createIndexContactEmail(
  contact_email: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, contact_email, 'contact_email'),
  ];

  return {
    fields: ['contact_email'],
    values
  };
}
/**
 * Create index for SchoolName fields
 */
function createIndexSchoolName(
  school_name: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, school_name, 'school_name'),
  ];

  return {
    fields: ['school_name'],
    values
  };
}
/**
 * Create index for CreateTime fields
 */
function createIndexCreateTime(
  create_time: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, create_time, 'create_time'),
  ];

  return {
    fields: ['create_time'],
    values
  };
}

export default DemoRequestORM;